/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eRpDQJ4lPmx
 */
import { Label } from "@/components/ui/label"
import { Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function UploadForm() {
  return (
    <div className="dark:bg-gray-800 dark:text-white grid w-full max-w-md items-center gap-4 p-4 rounded-lg shadow-lg">
      <h2 className="text-2xl font-bold">Select Your Option</h2>
      <p className="text-sm text-gray-500 dark:text-gray-400">
        Please select the option you want from the dropdown menu, upload your file, and click the submit button.
      </p>
      <div className="grid w-full items-center gap-1.5">
        <Label htmlFor="option-select">Options</Label>
        <Select className="dark:bg-gray-700 dark:text-white" id="option-select">
          <option value="">Select...</option>
          <option value="option1">Option 1</option>
          <option value="option2">Option 2</option>
          <option value="option3">Option 3</option>
        </Select>
      </div>
      <div className="grid w-full items-center gap-1.5">
        <Label htmlFor="file-upload">Upload File</Label>
        <Input className="dark:bg-gray-700 dark:text-white" id="file-upload" type="file" />
      </div>
      <Button className="bg-black dark:bg-white text-white dark:text-black" type="submit">
        Submit
      </Button>
    </div>
  )
}
